# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/TuviSRPLib/"                       # Path to '*.sln' directory
    schedule:
      interval: "daily"
      
  - package-ecosystem: "gitsubmodule"
    directory: "/"                                  # Path to '.gitmodules' directory
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"                                  # Workflow files stored in the default location
    schedule:
      interval: "monthly"
    groups:
      Common-actions:
        patterns:
          - "actions/*"
      Finebits-actions:
        patterns:
          - "finebits/*"
      GitHub-actions:
        patterns:
          - "github/*"
